version: "3.8"
services:
  db:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:27017
  microservice_1:
    build:
      context: ./microservice_1
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
